### ISSUE TITLE
Windows package not built for 2.15.05

### ISSUE THREAD

**Issue by rhpvorderman** [conda-forge/nasm-feedstock#16]
This is due to errors in the 2.15.05 nmake file. This issue can be closed once a new upstream release with a fixed nmake file is released.

**Comment by rhpvorderman** [comment]
Still doesn't work on 2.16. See https://github.com/conda-forge/nasm-feedstock/pull/19.

**Comment by arnabanimesh** [comment]
This issue has been resolved.

**Comment by jakirkham** [comment]
Done in PR: https://github.com/conda-forge/nasm-feedstock/pull/20
